# local evm rpc
rpc_url = "http://localhost:8545
# custom chain id
chain_id = 7700
# erc-20
contract_address = "0xDeE3F3A4135202E3e31A5EEd9bB771CDc5cf32e3"
# Second = Millisecond(1000) * Microsecond(1000) * Nanosecond(1000) * Duration(1)
waiting_time_for_transaction = 5000000000 